name: CI Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'before'
        run: ls

      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'After'
        run: ls
